# This is an appspec.yml template file for use with AWS CodeDeploy.
# The lines in this template starting with the hashtag symbol are
#   instructional comments and can be safely left in the file or
#   ignored.
# For help completing this file, see the "AppSpec File Reference" in the
#   "AWS CodeDeploy User Guide" at
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/arbiter
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/ec2/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/ec2/after_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/ec2/start.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/ec2/stop.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: scripts/ec2/validate.sh
      timeout: 60
      runas: ec2-user
