FROM 695135537037.dkr.ecr.us-east-1.amazonaws.com/thrivehive/linux:1.0.0

ARG APPLICATION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG CONTAINER_HOSTNAME
ARG DEVELOPER
ARG NODE_ENV

RUN yum update -y

# Create app directory
ADD . /usr/local/src/$APPLICATION
WORKDIR /usr/local/src/$APPLICATION

RUN yarn install
RUN bash ./scripts/docker/init_nginx.sh
RUN bash ./scripts/docker/init_config.sh
RUN service nginx start

RUN yarn run clean
RUN yarn build-dev

EXPOSE 3000
EXPOSE 3001
EXPOSE 9443
CMD [ "yarn", "pm2-dev", "process.dev.json", "--web", "3001" ]
